### ISSUE TITLE
Plugin doesn't support this project's cordova version. cordova: 3.8.0, failed version requirement: >=4.0.0

### ISSUE THREAD

**Issue by yyqangular1** [samilywang/cordova-baidupush#1]
安装插件时出现如下错误：
Plugin doesn't support this project's cordova version. cordova: 3.8.0, failed version requirement: >=4.0.0

目前cordova-ios才release到3.9，怎么出出现判断>=4.0.0的错误呢？
求解答，感谢！

**Comment by samilywang** [comment]
这边要求的是cordova的版本>=4.0.0, 不是cordova-ios的版本, 所以升级一下cordova的版本即可.
如果有各种神奇的原因无法升级corova版本, 请再与我联系, 谢谢关注~

**Comment by samilywang** [comment]
抱歉, 自行尝试了下, 在添加ios平台的时候, 确实是会报这样的错, 让我寻找一下原因

**Comment by yyqangular1** [comment]
@samilywang 我暂时修改了config文件，把这个版本检查先去掉了，感谢您的调查，期待结果：）

**Comment by samilywang** [comment]
@yyqangular1 感谢关注

根据[官方文档](http://cordova.apache.org/docs/en/5.1.1/plugin_ref/spec.html)中的这段解释:

> The <engine> tags also has default support for all of the main platforms Cordova exists on. Specifying the cordova engine tag means that all versions of Cordova on any platform must satisfy the engine version attribute. You may also list specific platforms and their versions in order to override the catch-all cordova engine

应该是我在设置`<engine>`的时候设置不当. 之前我以为`<engine>`里面cordova的值代表的是对cordova-cli版本的限制, 然而事实是对各个平台cordova.js的版本的限制. 所以才会出现这个报错.

目前已经将版本的限制改为>=3.0.0.

另外这个周末我应该会找时间同步一下百度云推送sdk的版本, 目前这个插件上的ios的sdk版本有点落后了.

**Comment by yyqangular1** [comment]
是的，这个引擎限制修改了就可以用了；多谢～
稍后是要升级ios9吗？

我自己也模仿着做了一个推送插件，ios在接受推送消息的那个方法总是报错，看起来和你的也没有什么不同，很奇怪…

发自我的 iPhone

**Comment by yyqangular1** [comment]
@samilywang 您好，我问个问题，请求您帮我解惑一下：
在您的插件中有如下文件：AppDelegate_BaiduPush.m，该文件中有方法didFinishLaunchingWithOptions，然而在启动文件AppDelegate.m中也有该方法，甚至其它插件中也有类似文件，目前debug时，只执行了AppDelegate_BaiduPush.m文件中的didFinishLaunchingWithOptions方法，AppDelegate.m文件中的同名方法不能被执行，请教一下，如何才能让其执行？？（因为里面有一些必须执行的代码）

**Comment by samilywang** [comment]
@yyqangular1 在这个插件中我是使用了objective-c的类别(category)特性, 具体的介绍可以看(这里)[https://zh.wikipedia.org/wiki/Objective-C]

**Comment by samilywang** [comment]
@yyqangular1 在这个插件中我是使用了objective-c的类别(category), 具体可以看[这里](https://zh.wikipedia.org/wiki/Objective-C).

> 若分类声明了与类中原有方法同名的函数，则分类中的方法会被调用。因此分类不仅可以增加类的方法，也可以代替原有的方法。这个特性可以用于修正原有代码中的错误，更可以从根本上改变程序中原有类的行为。若两个分类中的方法同名，则被调用的方法是不可预测的。

目前你所说的那种情况...我好像暂时没有特别好的、优雅的解决方案...一种解决方法是直接把那些必须执行的代码放到`AppDelegate_BaiduPush.m`中, 还有一种就是不使用这个插件, 然后根据百度云推送的[SDK集成步骤](http://push.baidu.com/doc/ios/api)去修改`AppDelegate.m`中的`didFinishLaunchingWithOptions`, 把百度云推送相关的逻辑添加进去.

这个问题我会持续关注, 如果有更好的解决方法, 我会及时告知.

另外你是在做一个cordova的项目么? 推荐最好不要去直接修改原生部分的代码, 尽量通过插件的形式去实现原生部分的功能.

**Comment by yyqangular1** [comment]
@samilywang 是的，现在在做cordova的项目，因为我没学过oc，所以不太懂AppDelegate_BaiduPush.m或者AppDelegate+BaiduPush.m这种文件应该怎么使用，因此我全部都写到了AppDelegate.m文件中了；
后面用的插件多了，发现问题很大，耦合行太高了，platform一旦删除，所有代码都没有了。
但是现在却是不太懂AppDelegate_BaiduPush.m这种文件是根据什么原理创建的，什么样的执行顺序，有关于这块的教程或者文档，求推荐一下～
