### ISSUE TITLE
Android App crashed

### ISSUE THREAD

**Issue by ryanlin1986** [samilywang/cordova-baidupush#2]
When I call  window.baidupush.startWork, the app crashed.

Here is the output:
E/CommandListener(  154): readDefRoute call readDefRoute
E/SecondaryTablController(  154): isWifiDefaultRouteExisted /system/bin/ip route
E/CommandListener(  154): readDefRoute Rsp ok
W/RegistrationService( 4908): Already binded, no need to bind anymore
W/dalvikvm( 1408): threadid=1: thread exiting with uncaught exception (group=0x419d6c68)
I/logserver(  294): Object Path:/data/system/dropbox/, mask=0x00000080
I/logserver(  294): event->len=48, name=data_app_crash@1446542036730.txt
I/logserver(  294): find_first_match: find match, plogs(type=1, pfile=/data/system/dropbox/, match=app_crash)
I/logserver(  294): move_dir:src_path=/data/log/dbox/appdbg/logcache
I/logserver(  294): move_dir:dst_path=/data/log/logcache/15427176/
I/logserver(  294): is_all_ready, any file is ready in non-keyfile exception.
I/logserver(  294): extract_appname, forward search, appname=com.dahua.tigerapp
I/logserver(  294): archive_and_send, pos=0, type=crash, output=20151103171356_crash
I/logserver(  294): ---copy_match_files enter!!--
I/logserver(  294): [copy_match_files,829]: copy [/data/system/dropbox/data_app_crash@1446542036730.txt] to [/data/log/logcache/15427176/data_app_crash@1446542036730.txt]
I/logserver(  294): internal_archive, argc=7
I/logserver(  294): get_fault_appname, appname=com.dahua.tigerapp
I/logserver(  294): handle_archive_exception, argc=7
I/logserver(  294): get alarm time = 1107484 (sec.)!

**Comment by samilywang** [comment]
Can you provide more information? Such as the operating system, cordova version, which tool you use for developing and the code where you call the window.baidupush.startWork ?

**Comment by samilywang** [comment]
OK, I think I have found where goes wrong in android.

I forget to catch JSON Exception thrown by a json parse function.

I will fix this bug as soon as possible.

**Comment by ryanlin1986** [comment]
Thanks, waiting for your upcoming fix.

**Comment by samilywang** [comment]
Fixed.

If the error still occurs, please let me know.

**Comment by ryanlin1986** [comment]
Still, the app crashed( only in first time app starts, after crash and open app again, no crash ),I think it's something todo with install the baidu background service or something.
Here is the updated log:

E/dalvikvm(10419): could not disable core file generation for pid 10419: Operation not permitted
I/Process (10419): Sending signal. PID: 10419 SIG: 9
E/dalvikvm(10451): could not disable core file generation for pid 10451: Operation not permitted
I/Process (10451): Sending signal. PID: 10451 SIG: 9
I/System.out( 5236): encode =  1
I/MultiDex(10478): VM with version 1.6.0 does not have multidex support
I/MultiDex(10478): install
I/MultiDex(10478): MultiDexExtractor.load(/data/app/com.baidu.BaiduMap-1.apk, false)
I/MultiDex(10478): loading existing secondary dex files
I/MultiDex(10478): load found 1 secondary dex files
I/MultiDex(10478): install done
E/dalvikvm(10497): could not disable core file generation for pid 10497: Operation not permitted
I/Process (10478): Sending signal. PID: 10478 SIG: 9
W/dalvikvm(10262): threadid=1: thread exiting with uncaught exception (group=0x4175fc50)

**Comment by ryanlin1986** [comment]
In plugin.xml, found the wrong package prefix com.lyee, chagned it to the right package prefix, now it's fixed.

**Comment by samilywang** [comment]
Got it. I have fix the wrong package prefix. Thanks.
