### ISSUE TITLE
部分机型调用startwork时卡死

### ISSUE THREAD

**Issue by ryanlin1986** [samilywang/cordova-baidupush#4]
初步研究了下代码， 发现里面用了线程锁之类的东西， 感觉是这块引起的， cordova调用应该尽快直接返回不要阻塞线程， 如果一定要也需要通过callback方式。

**Comment by samilywang** [comment]
了解, 之前加锁是因为考虑到调用startwork之后立即调用其余函数比如setTag会有报错的情况出现, 所以采用了锁来限定执行顺序
最近略忙, 估计修复要周末的时候, 抱歉~

**Comment by ryanlin1986** [comment]
感谢；）

**Comment by samilywang** [comment]
@ryanlin1986 我已经把去除线程锁的代码提交到了bugfix/issue分支上, 不过没有经过测试, 你可以测试下这个分支下的代码是否还会导致卡死的问题
